# Generated by Django 5.1.6 on 2025-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
