# Generated by Django 5.1.1 on 2025-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megazine', '0003_aboutfounder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlespage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Image/')),
            ],
        ),
    ]
